
apiVersion: v1
kind: Pod

metadata:
  name: weather-app-pod
  labels:
    app: weather-app

spec:
  containers:
    - name: weather-app
      image: dhirajpatil2757/weather-app:1.0
      imagePullPolicy: Always

      ports:
        - containerPort: 5000

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"